"""empty message

Revision ID: 109c27ec23c6
Revises: bcd5278a5a3b
Create Date: 2020-07-09 13:28:16.560211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '109c27ec23c6'
down_revision = 'bcd5278a5a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uid_friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uid_friend_uid'), 'uid_friend', ['uid'], unique=True)
    op.drop_index('ix_element_uid', table_name='element')
    op.drop_table('element')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('element',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('uid', mysql.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_element_uid', 'element', ['uid'], unique=True)
    op.drop_index(op.f('ix_uid_friend_uid'), table_name='uid_friend')
    op.drop_table('uid_friend')
    # ### end Alembic commands ###
