"""empty message

Revision ID: bcd5278a5a3b
Revises: c706afe7fa2e
Create Date: 2020-07-09 13:26:47.839067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcd5278a5a3b'
down_revision = 'c706afe7fa2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('element', sa.Column('uid', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_element_uid'), 'element', ['uid'], unique=True)
    op.drop_index('ix_element_text_element', table_name='element')
    op.drop_column('element', 'text_element')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('element', sa.Column('text_element', mysql.VARCHAR(length=500), nullable=True))
    op.create_index('ix_element_text_element', 'element', ['text_element'], unique=True)
    op.drop_index(op.f('ix_element_uid'), table_name='element')
    op.drop_column('element', 'uid')
    # ### end Alembic commands ###
