"""empty message

Revision ID: c706afe7fa2e
Revises: 868d357c3cfc
Create Date: 2020-07-09 13:14:47.534057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c706afe7fa2e'
down_revision = '868d357c3cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_element', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_element_text_element'), 'element', ['text_element'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_element_text_element'), table_name='element')
    op.drop_table('element')
    # ### end Alembic commands ###
